name: AI Test SCM Pipeline
on:
  push:
    branches:
      - main

jobs:
  show-commit-id:
    runs-on: ubuntu-latest

    steps:
      # Repo'yu checkout et
      - name: Checkout repo
        uses: actions/checkout@v3

      # Merge sonrası son commit ID'yi göster
      - name: Show latest commit ID
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          echo "New commit ID after merge: $COMMIT_ID"

      # merge sonrası degisen dosyaları github api ile alma
      - name: Get changed files via GitHub API
        run: |
          BEFORE=${{ github.event.before }}
          SHA=${{ github.sha }}

          # Eğer BEFORE boşsa main branch ile karşılaştır
          if [ -z "$BEFORE" ]; then
            BEFORE="main"
          fi

          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/kasimes/AI_TESTGEN/compare/$BEFORE...$SHA \
          > diff.json

      # Merge sonrası değişen dosyaları listele
      - name: List changed files
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD

      #  Değişen dosyaları göster
      - name: Show diff json
        run: cat diff.json

      - name: Show only changed files names
        run: |
          jq -r '.files[].filename' diff.json || paste -sd "--"
      - name: Extract changed files
        run: |
          cat diff.json | jq -r '.files[].filename' > changed_files.json
          cat changed_files.json

      - name: Run dff_parser.py to exrtract changed files
        run: python listener/dff_parser.py

      - name: run endpoint_extractor.py to extract endpoints from changed files
        run: python listener/endpoint_extractor.py

      - name: Upload changed files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: |
            changed_files.json
            diff.json
