
name: AI Test SCM Pipeline
on:
   pull_request:
     types:[closed]


jobs:
    show-commit-id:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

       steps:
      # Repo'yu checkout et
      - name: Checkout repo
        uses: actions/checkout@v3

      # Merge sonrası son commit ID'yi göster
      - name: Show latest commit ID
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          echo "New commit ID after merge: $COMMIT_ID"

      # (Opsiyonel) Merge sonrası değişen dosyaları listele
      - name: List changed files
        run: |
          git fetch origin
          git diff --name-only HEAD~1 HEAD